# Generated by Django 4.1.3 on 2022-12-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parsing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actordata",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="moviedata",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="IMAGE"),
        ),
    ]
